Import Numpy and check the version

In [2]:
import numpy as np
np.__version__

'1.26.4'

Create a Python list than convert convert it to a Numpy array and check its type

In [4]:
my_list = [1, 2, 3, 4, 5]
my_array = np.array(my_list)
print(type(my_array))

<class 'numpy.ndarray'>


Create a 1D array of 10 zeros and 10 ones

In [6]:
zeros_array = np.zeros(10)
print(zeros_array)
ones_array = np.ones(10)
print(ones_array)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


Create a 3x3 identity matrix

In [7]:
identity_matrix = np.eye(3)
print(identity_matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Create an array of numbers from 10 to 50 and reverse it

In [8]:
array = np.arange(10, 51)
reversed_array = array[::-1]
print(reversed_array)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


Create a 4x4 matrix with values ranging from 0 to 15

In [14]:
matrix_4x4 = np.arange(16).reshape(4, 4)
print(matrix_4x4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Find the indices of non-zero elements in the array

In [11]:
array = np.array([0,1,6,0,9,3,5,0])
non_zero_indices = np.nonzero(array)
print(non_zero_indices[0])

[1 2 4 5 6]


Create a 5x5 matrix with 1 on the border and 0 inside

In [15]:
matrix_5x5 = np.ones((5, 5))
matrix_5x5[1:-1, 1:-1] = 0
print(matrix_5x5)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


Create a 3x3 matrix with random values between 0 to 10 and find the minimum and maximum values

In [19]:
matrix_3x3_random = np.random.randint(0, 11, size=(3, 3))
print(matrix_3x3_random)
min_value = np.min(matrix_3x3_random)
max_value = np.max(matrix_3x3_random)
print("Minimum value:", min_value)
print("Maximum value:", max_value)

[[7 2 8]
 [9 4 8]
 [2 9 6]]
Minimum value: 2
Maximum value: 9


Normalize the random matrix from the exercise 9 between 0 and 1

In [22]:
matrix_normalized = (matrix_3x3_random - min_value) / (max_value - min_value)
print(matrix_normalized)

[[0.71428571 0.         0.85714286]
 [1.         0.28571429 0.85714286]
 [0.         1.         0.57142857]]


Multiply a 5x3 matrix by a 3x2 matrix (matrix product)

In [43]:
matrix_5x3 = np.random.randint(1, 11, size=(5,3))
matrix_3x2 = np.random.randint(1, 11, size=(3,2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print("5x3 Matrix:\n", matrix_5x3)
print("3x2 Matrix:\n", matrix_3x2)
print("Product Matrix:\n", product_matrix)


5x3 Matrix:
 [[ 2  9  7]
 [10  1  7]
 [ 6  7  1]
 [ 6 10  3]
 [ 3  6  3]]
3x2 Matrix:
 [[10  2]
 [ 3  7]
 [ 6  2]]
Product Matrix:
 [[ 89  81]
 [145  41]
 [ 87  63]
 [108  88]
 [ 66  54]]


Extract the integer part of a random array

In [52]:
random_array = np.random.uniform(0, 10, size=5)
print("Random Array:", random_array)
integer_part = np.floor(random_array)
print("Integer Part:", integer_part)

Random Array: [0.05509184 8.19291817 6.70673384 1.00226308 9.21371714]
Integer Part: [0. 8. 6. 1. 9.]


Check if two arrays are equal

In [65]:
input1 = input("Enter the first array (Comma seperated): ")
array1 = np.array([float(x) for x in input1.split(',')])

input2 = input("Enter the second array (Comma seperated): ")
array2 = np.array([float(x) for x in input2.split(',')])

equal = np.array_equal(array1, array2)

if equal:
    print("Equal")
else:
    print("Not Equal.")

Enter the first array (Comma seperated): 0.1, 1,2
Enter the second array (Comma seperated): 0.1, 1, 2
Equal


Find the unique elements of an array

In [66]:
sample_array = np.array([0, 1, 1, 2, 2, 3, 4, 4, 4, 5])
uniqe_elements = np.unique(sample_array)
print(uniqe_elements)

[0 1 2 3 4 5]


Find the number of occurrences of each value in an array

In [73]:
unique_elements, counts = np.unique(sample_array, return_counts=True)

#zip fonksiyonu iki veya daha fazla diziyi gruplamak için kullanılır.
for element, count in zip(unique_elements, counts):
    print(f"Value: {element}, Count: {count}")

Value: 0, Count: 1
Value: 1, Count: 2
Value: 2, Count: 2
Value: 3, Count: 1
Value: 4, Count: 3
Value: 5, Count: 1


Replace the maximum value in a 2D array with 0

In [80]:
array_2d = np.array([[1,2],
                      [3,4]])
max_value = np.max(array_2d)
array_2d[array_2d == max_value] = 0
print(array_2d)

[[1 2]
 [3 0]]


 Convert a 1D array to a 2D array with 3 rows

In [88]:
array_1d = np.arange(12)
array_2d = array_1d.reshape(3, -1)
print(array_2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


 Create a random 4x4 matrix and compute the row-wise and column-wise sums

In [94]:
random_matrix_4x4 = np.random.rand(4, 4)
print("Random 4x4 Matrix:\n", random_matrix_4x4)

row_sums = np.sum(random_matrix_4x4, axis=1)
print("\nRow-wise sums:", row_sums)

column_sums = np.sum(random_matrix_4x4, axis=0)
print("\nColumn-wise sums:", column_sums)

Random 4x4 Matrix:
 [[0.10056459 0.00207365 0.17733031 0.16534946]
 [0.30100063 0.45049738 0.09948746 0.41001042]
 [0.82799713 0.98660658 0.37496985 0.65649829]
 [0.87062013 0.2541706  0.57232304 0.76262916]]

Row-wise sums: [0.44531802 1.26099588 2.84607185 2.45974293]

Column-wise sums: [2.10018249 1.69334821 1.22411065 1.99448733]
