# Exercise 1: Import Numpy and check the version

In [37]:
import numpy as np
print(np.__version__)

2.1.2


# Exercise 2: Create a Python list than convert convert it to a Numpy array and check its type

In [38]:
py_list = [1, 2, 3, 4, 5]
np_array = np.array(py_list)
print(type(np_array))

<class 'numpy.ndarray'>


# Exercise 3: Create a 1D array of 10 zeros and 10 ones

In [39]:
zeros = np.zeros(10)
ones = np.ones(10)
print(zeros)
print(ones)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


# Exercise 4: Create a 3x3 identity matrix

In [40]:
identity_matrix = np.eye(3)
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


# Exercise 5: Create an array of numbers from 10 to 50 and reverse it

In [41]:
array = np.arange(10, 51)


reversed_array = array[::-1]

print(reversed_array)

[50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27
 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


# Exercise 6: Create a 4x4 matrix with values ranging from 0 to 15

In [42]:
matrix_4x4 = np.arange(16).reshape(4, 4)
print(matrix_4x4)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


# Exercise 7: Find the indices of non-zero elements in the array


In [28]:
array_with_zeros = [1, 2, 0, 0, 4, 0]
non_zero_indices = np.nonzero(array_with_zeros)
print(non_zero_indices)

(array([0, 1, 4]),)


# Exercise 8: Create a 5x5 matrix with 1 on the border and 0 inside

In [32]:
matrix_5x5 = np.ones((5, 5))
matrix_5x5[1:-1, 1:-1] = 0
print(matrix_5x5)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Exercise 9: Create a 3x3 matrix with random values between 0 to 10 and find the minimum and maximum values

In [33]:
random_matrix = np.random.randint(0, 11, (3, 3))
min_val = random_matrix.min()
max_val = random_matrix.max()
print(random_matrix)
print("Min:", min_val)
print("Max:", max_val)

[[7 6 6]
 [7 9 0]
 [6 6 3]]
Min: 0
Max: 9


# Exercise 10: Normalize the random matrix from the exercise 9 between 0 and 1

In [34]:
normalized_matrix = (random_matrix - min_val) / (max_val - min_val)
print(normalized_matrix)

[[0.77777778 0.66666667 0.66666667]
 [0.77777778 1.         0.        ]
 [0.66666667 0.66666667 0.33333333]]


# Exercise 11: Multiply a 5x3 matrix by a 3x2 matrix (matrix product)

In [12]:
matrix_5x3 = np.random.random((5, 3))
matrix_3x2 = np.random.random((3, 2))
product_matrix = np.dot(matrix_5x3, matrix_3x2)
print(product_matrix)

[[0.31840525 0.27442911]
 [1.05597676 1.04618105]
 [0.86524934 1.09673268]
 [0.50372455 0.73085224]
 [0.98325785 1.23624868]]


# Exercise 12: Extract the integer part of a random array

In [13]:
random_array = np.random.random(5) * 10
integer_part = np.floor(random_array)
print(integer_part)

[0. 3. 0. 3. 7.]


# Exercise 13: Check if two arrays are equal

In [14]:
array1 = np.array([1, 2, 3])
array2 = np.array([1, 2, 3])
are_equal = np.array_equal(array1, array2)
print(are_equal)

True


# Exercise 14: Find the unique elements of an array

In [15]:
array_with_duplicates = np.array([1, 2, 2, 3, 3, 3])
unique_elements = np.unique(array_with_duplicates)
print(unique_elements)


[1 2 3]


# Exercise 15: Find the number of occurrences of each value in an array

In [16]:
occurrences = np.bincount(array_with_duplicates)
print(occurrences)

[0 1 2 3]


# Exercise 16: Replace the maximum value in a 2D array with 0

In [17]:
array_2D = np.random.random((3, 3)) * 10
array_2D[array_2D == array_2D.max()] = 0
print(array_2D)

[[2.72038216 5.51292193 0.63964983]
 [0.         8.59347304 4.64743328]
 [0.09617938 8.7518081  8.15271339]]


# Exercise 17: Convert a 1D array to a 2D array with 3 rows

In [18]:
array_1D = np.arange(9)
array_2D = array_1D.reshape(3, 3)
print(array_2D)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


# Exercise 18: Create a random 4x4 matrix and compute the row-wise and column-wise sums

In [43]:
random_matrix_4x4 = np.random.random((4, 4))
row_sums = random_matrix_4x4.sum(axis=1)
column_sums = random_matrix_4x4.sum(axis=0)
print("Matrix:\n", random_matrix_4x4)
print("Row sums:", row_sums)
print("Column sums:", column_sums)

Matrix:
 [[0.79676158 0.53971544 0.82163011 0.6835182 ]
 [0.30012326 0.52663901 0.97817619 0.18555324]
 [0.9793097  0.42368566 0.09852923 0.94729847]
 [0.74618747 0.63782178 0.33553155 0.37860457]]
Row sums: [2.84162532 1.9904917  2.44882306 2.09814537]
Column sums: [2.82238201 2.1278619  2.23386708 2.19497447]
